### ISSUE TITLE
Output Class Labels

### ISSUE THREAD

**Issue by Awais-commit** [evtimovi/robust_physical_perturbations#7]
After running manyclassify.py, it gives me top 3 predicitions for all the images. But I don't understand the class labels that it assigns for example, for image 28.png the output class lables returned are14, 8, 17. Where are these labels defined and what do they mean? How can I change the target class for the stop sign?

**Comment by evtimovi** [comment]
I just added `mapping.txt` under `lisa-cnn-attack` in commit 3810af06bb0c93b4da94f0aa3e066b5f8d0cd8d0 You can confirm if it is correct by running clean images through the network and comparing the expected label to what the network spits out. Because it has been a while and I might have copied the wrong file, they might be one off; if so, please, feel free to reopen and I will look for the correct file.

**Comment by Awais-commit** [comment]
Hey, thanks for your help and for providing the list. I have seen the text file but there is the Issue that the model always classifies the images to the "Class 14"  with the highest probability and "Class 14" belongs to "Stop Sign" which means it classifies stop sign as stop sign whereas it should actually misclassify the stop sign as something else.
Also, I would like to know how to set a target class of my choosing so that the network will always return the class of my choice?
